### ISSUE TITLE
redis Cluster Support - No Id Generated -Id Generation failed after 5 retries

### ISSUE THREAD

**Issue by ashishsoni** [intenthq/icicle#8] opened 2015-08-03 20:45 UTC
Hi , 
When i try to connect to cluster on port 7001 i am getting below error it works when i connect on individual node on port 6379 , Not sure what is the issue , Please help

**Comment by janstenpickle** [comment] 2015-08-03 21:03
Can you paste the code you are using to set up the ID generator please?

**Comment by ashishsoni** [comment] 2015-08-03 21:05
import java.util.Arrays;
import java.util.List;

import com.google.common.base.Optional;
import com.intenthq.icicle.IcicleIdGenerator;
import com.intenthq.icicle.Id;
import com.intenthq.icicle.JedisIcicle;
import com.intenthq.icicle.redis.Redis;
import com.intenthq.icicle.redis.RoundRobinRedisPool;


public class TestIdGenerator {

	public static void main(String[] args) {
		
		
//		Redis redisServerOne = new JedisIcicle("10.200.37.106:7001");
		Redis redisServerTwo = new JedisIcicle("10.200.37.106:7001");
//		Redis redisServerThree = new JedisIcicle("10.200.37.178:7002");
		List<Redis> redises = Arrays.asList(redisServerTwo);

		RoundRobinRedisPool roundRobinRedisPool = new RoundRobinRedisPool(redises);
		IcicleIdGenerator icicleIdGenerator = new IcicleIdGenerator(roundRobinRedisPool);
//		Optional<List<Id>> ids = icicleIdGenerator.generateIdBatch(20);
		
		for(;;) {
		Optional<Id> id = icicleIdGenerator.generateId();
		
		System.out.println(id.get());
	}

		

	}

}

**Comment by janstenpickle** [comment] 2015-08-03 21:11
The code looks OK (I assume you're half way through testing). It's the same as we are using in production so will work, the only thing that I can think may be wrong is firewall rules between your machines. Have you tried poking the remote ports with telnet?

**Comment by ashishsoni** [comment] 2015-08-03 21:14
when i use redis-cli from a different machine i can connect so that means the ports are open not sure if it will work only with individual nodes
redis-cli -h 10.200.37.106 -p 7001

**Comment by janstenpickle** [comment] 2015-08-03 21:30
That's very odd, I've just tried it locally with a server on port 7001 and it works fine. Could you provide more details of the error you are seeing please?

**Comment by ashishsoni** [comment] 2015-08-04 17:21
Ya it works on independent node but it does not work with Cluster , Did you try redis 3.0.3 with cluster mode.
I am getting below error

103 [main] ERROR com.intenthq.icicle.IcicleIdGenerator - No ID generated. ID generation failed after 5 retries.
Exception in thread "main" java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:47)
	at com.ericsson.metratech.idmanager.TestIdGenerator.main(TestIdGenerator.java:31)

**Comment by janstenpickle** [comment] 2015-08-05 17:50
Ahh I see what the problem is. The redis library (jedis) our provided implementation for our redis interface  does not support redis cluster. The nodes in the configuration should be configured to be standalone, they do not need to share state anyway, so a cluster configuration is unnecessary at this point.

To solve your problem quickly, set up you redis nodes as standalone instances. However if you wish to add redis cluster support to the Icicle project we would very much welcome contributions via pull request :smiley:.

**Comment by nathankleyn** [comment] 2015-08-11 09:48
Just seen that you've opened xetorthio/jedis#1081 which has been closed with the following comment:

>  you have to use the latest code available in the master branch. We haven't released a version with this functionality yet.

In lieu of support in Jedis for Redis cluster, we only (currently) support Redis in standalone mode. As such, for now, I will close this issue - please feel free to reopen if you're still having issues. :smiley:

**Closed by nathankleyn** 2015-08-11 09:48 UTC
Labels: help wanted
